FROM centos:7.6
 
RUN rpm -i https://mirrors.aliyun.com/remi/enterprise/remi-release-7.rpm --nodeps \
    && rpm -i https://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm \
    && yum install -y  php php-memcached php-fpm php-mysql php-pdo php-redis \ 
        php-dom php-gd php-mbstring php-mcrypt --enablerepo=remi-php73 \
    && yum clean all \
 
EXPOSE 9000
 
CMD ["/usr/sbin/php-fpm","--nodaemonize"]
